version: '3.9'

services:
  web:
    build: .  # Usa el Dockerfile per construir la imatge
    container_name: php_apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    # environment:
    #  - APACHE_DOCUMENT_ROOT=/var/www/html/public
    restart: unless-stopped
